version: '3.8'
services:
  admin.backend:
    build:
      context: ./admin
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - ./admin:/app
    depends_on:
      - admin.db
      - rabbitmq

  admin.queue:
    build:
      context: ./admin
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - admin.db

  admin.db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./admin/.dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  main.backend:
    build:
      context: ./main
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - ./main:/app
    depends_on:
      - main.db
      - rabbitmq

  main.queue:
    build:
      context: ./main
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - main.db

  main.db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./main/.dbdata:/var/lib/mysql
    ports:
      - 33067:3306

  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
