version: '3.8'
services:
  admin_backend:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./admin:/app
    depends_on:
      - admin_db
      - rabbitmq

  admin_db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./admin/.dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  main_backend:
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - 8001:5000
    volumes:
      - ./main:/app
    depends_on:
      - main_db
      - rabbitmq

  main_db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./main/.dbdata:/var/lib/mysql
    ports:
      - 33067:3306

  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
